-- MySQL Script generated by MySQL Workbench
-- Thu Mar 17 07:47:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema travellingagencydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema travellingagencydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `travellingagencydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `travellingagencydb` ;

-- -----------------------------------------------------
-- Table `travellingagencydb`.`vacationdestination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travellingagencydb`.`vacationdestination` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `description` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 387
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travellingagencydb`.`vacationpackages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travellingagencydb`.`vacationpackages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vacationlocation` INT NOT NULL,
  `price` INT NOT NULL,
  `numberOfPeople` INT NOT NULL,
  `details` VARCHAR(1024) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `status` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_destionation_id_idx` (`vacationlocation` ASC) VISIBLE,
  CONSTRAINT `fk_destionation_id`
    FOREIGN KEY (`vacationlocation`)
    REFERENCES `travellingagencydb`.`vacationdestination` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 127
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travellingagencydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travellingagencydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `username` VARCHAR(128) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `userRole` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 590
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travellingagencydb`.`bookedpackages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travellingagencydb`.`bookedpackages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `packageID` INT NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_id_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_package_id_idx` (`packageID` ASC) VISIBLE,
  CONSTRAINT `fk_package_id`
    FOREIGN KEY (`packageID`)
    REFERENCES `travellingagencydb`.`vacationpackages` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`userID`)
    REFERENCES `travellingagencydb`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
